# Generated by Django 4.2.16 on 2024-11-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='bio',
            field=models.CharField(default='A wonderul team member!', max_length=1000),
        ),
    ]
