# Generated by Django 4.2.16 on 2024-11-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_alter_teammember_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='jobtitle',
            field=models.CharField(max_length=50, verbose_name='Job Title'),
        ),
    ]
