# Generated by Django 4.2.16 on 2024-11-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_alter_teammember_jobtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='status',
            field=models.IntegerField(choices=[(0, 'Team Member'), (1, 'Owner')], default=0),
        ),
    ]
