# Generated by Django 4.2.16 on 2024-11-05 16:55

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(default='Ingredients needed', max_length=10000),
        ),
        migrations.AddField(
            model_name='recipe',
            name='method',
            field=models.TextField(default='Method needed', max_length=10000),
        ),
    ]
