# Generated by Django 4.2.16 on 2024-11-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_recipe_featured_image_recipe_ingredients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.IntegerField(default=4, help_text='Enter how many people your recipes serves.'),
        ),
    ]
