# Generated by Django 4.2.16 on 2024-11-09 18:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_recipe_servings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='static/images/recipe-default-image.png', max_length=255, verbose_name='image'),
        ),
    ]
