# Generated by Django 4.2.16 on 2024-11-09 19:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_recipe_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dbtrgpmbu/image/upload/v1731179066/recipe-default-image_tmh79i.png', max_length=255, verbose_name='image'),
        ),
    ]
