# Generated by Django 4.2.16 on 2024-11-22 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_recipe_team_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='team_member',
        ),
    ]
