# Generated by Django 4.2.16 on 2024-11-24 10:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_recipe_team_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(500)]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(default='Ingredients needed'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='method',
            field=models.TextField(default='Method needed'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=55, unique=True),
        ),
    ]
